<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/command/command.proto

namespace Bluehead\V2ray\Core\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.command.AddInboundRequest</code>
 */
class AddInboundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     */
    private $inbound = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\InboundHandlerConfig $inbound
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     * @return \Bluehead\V2ray\Core\InboundHandlerConfig
     */
    public function getInbound()
    {
        return $this->inbound;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     * @param \Bluehead\V2ray\Core\InboundHandlerConfig $var
     * @return $this
     */
    public function setInbound($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\InboundHandlerConfig::class);
        $this->inbound = $var;

        return $this;
    }

}

