<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/command/command.proto

namespace Bluehead\V2ray\Core\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.command.AlterInboundRequest</code>
 */
class AlterInboundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    private $tag = '';
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage operation = 2;</code>
     */
    private $operation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage $operation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage operation = 2;</code>
     * @return \Bluehead\V2ray\Core\Common\Serial\TypedMessage
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage operation = 2;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->operation = $var;

        return $this;
    }

}

