<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/srtp/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Srtp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb020a2c7472616e73706f72742f696e7465726e65742f686561646572" .
            "732f737274702f636f6e6669672e70726f746f1233626c7565686561642e" .
            "76327261792e636f72652e7472616e73706f72742e696e7465726e65742e" .
            "686561646572732e7372747022770a06436f6e666967120f0a0776657273" .
            "696f6e18012001280d120f0a0770616464696e6718022001280812110a09" .
            "657874656e73696f6e18032001280812120a0a637372635f636f756e7418" .
            "042001280d120e0a066d61726b657218052001280812140a0c7061796c6f" .
            "61645f7479706518062001280d42650a2e636f6d2e76327261792e636f72" .
            "652e7472616e73706f72742e696e7465726e65742e686561646572732e73" .
            "72747050015a0473727470aa022a56325261792e436f72652e5472616e73" .
            "706f72742e496e7465726e65742e486561646572732e5372747062067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

