<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dispatcher/config.proto

namespace Bluehead\V2ray\GPBMetadata\App\Dispatcher;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a1b6170702f646973706174636865722f636f6e6669672e70726f" .
            "746f1222626c7565686561642e76327261792e636f72652e6170702e6469" .
            "737061746368657222150a0d53657373696f6e436f6e6669674a04080110" .
            "02224d0a06436f6e66696712430a0873657474696e677318012001280b32" .
            "312e626c7565686561642e76327261792e636f72652e6170702e64697370" .
            "6174636865722e53657373696f6e436f6e66696742490a1d636f6d2e7632" .
            "7261792e636f72652e6170702e6469737061746368657250015a0a646973" .
            "70617463686572aa021956325261792e436f72652e4170702e4469737061" .
            "7463686572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

