<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Tcp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.tcp.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage header_settings = 2;</code>
     */
    private $header_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage $header_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Transport\Internet\Tcp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage header_settings = 2;</code>
     * @return \Bluehead\V2ray\Core\Common\Serial\TypedMessage
     */
    public function getHeaderSettings()
    {
        return $this->header_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage header_settings = 2;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setHeaderSettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->header_settings = $var;

        return $this;
    }

}

