<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/srtp/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Headers\Srtp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.headers.srtp.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    private $version = 0;
    /**
     * Generated from protobuf field <code>bool padding = 2;</code>
     */
    private $padding = false;
    /**
     * Generated from protobuf field <code>bool extension = 3;</code>
     */
    private $extension = false;
    /**
     * Generated from protobuf field <code>uint32 csrc_count = 4;</code>
     */
    private $csrc_count = 0;
    /**
     * Generated from protobuf field <code>bool marker = 5;</code>
     */
    private $marker = false;
    /**
     * Generated from protobuf field <code>uint32 payload_type = 6;</code>
     */
    private $payload_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type bool $padding
     *     @type bool $extension
     *     @type int $csrc_count
     *     @type bool $marker
     *     @type int $payload_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Transport\Internet\Headers\Srtp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool padding = 2;</code>
     * @return bool
     */
    public function getPadding()
    {
        return $this->padding;
    }

    /**
     * Generated from protobuf field <code>bool padding = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPadding($var)
    {
        GPBUtil::checkBool($var);
        $this->padding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool extension = 3;</code>
     * @return bool
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Generated from protobuf field <code>bool extension = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setExtension($var)
    {
        GPBUtil::checkBool($var);
        $this->extension = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 csrc_count = 4;</code>
     * @return int
     */
    public function getCsrcCount()
    {
        return $this->csrc_count;
    }

    /**
     * Generated from protobuf field <code>uint32 csrc_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCsrcCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->csrc_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool marker = 5;</code>
     * @return bool
     */
    public function getMarker()
    {
        return $this->marker;
    }

    /**
     * Generated from protobuf field <code>bool marker = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setMarker($var)
    {
        GPBUtil::checkBool($var);
        $this->marker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 payload_type = 6;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payload_type;
    }

    /**
     * Generated from protobuf field <code>uint32 payload_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkUint32($var);
        $this->payload_type = $var;

        return $this;
    }

}

