<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Headers\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.headers.http.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * "Accept", "Cookie", etc
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Each entry must be valid in one piece. Random entry will be chosen if multiple entries present.
     *
     * Generated from protobuf field <code>repeated string value = 2;</code>
     */
    private $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           "Accept", "Cookie", etc
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $value
     *           Each entry must be valid in one piece. Random entry will be chosen if multiple entries present.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * "Accept", "Cookie", etc
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * "Accept", "Cookie", etc
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Each entry must be valid in one piece. Random entry will be chosen if multiple entries present.
     *
     * Generated from protobuf field <code>repeated string value = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Each entry must be valid in one piece. Random entry will be chosen if multiple entries present.
     *
     * Generated from protobuf field <code>repeated string value = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->value = $arr;

        return $this;
    }

}

