<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/http/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Headers\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.headers.http.ResponseConfig</code>
 */
class ResponseConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    private $version = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Status status = 2;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.transport.internet.headers.http.Header header = 3;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Version $version
     *     @type \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Status $status
     *     @type \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Header[]|\Google\Protobuf\Internal\RepeatedField $header
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     * @return \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Version
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     * @param \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Version $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Version::class);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Status status = 2;</code>
     * @return \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.headers.http.Status status = 2;</code>
     * @param \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.transport.internet.headers.http.Header header = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.transport.internet.headers.http.Header header = 3;</code>
     * @param \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Header[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\Transport\Internet\Headers\Http\Header::class);
        $this->header = $arr;

        return $this;
    }

}

