<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/wireguard/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Wireguard;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a317472616e73706f72742f696e7465726e65742f686561646572" .
            "732f7769726567756172642f636f6e6669672e70726f746f1238626c7565" .
            "686561642e76327261792e636f72652e7472616e73706f72742e696e7465" .
            "726e65742e686561646572732e77697265677561726422110a0f57697265" .
            "6775617264436f6e66696742740a33636f6d2e76327261792e636f72652e" .
            "7472616e73706f72742e696e7465726e65742e686561646572732e776972" .
            "65677561726450015a09776972656775617264aa022f56325261792e436f" .
            "72652e5472616e73706f72742e496e7465726e65742e486561646572732e" .
            "576972656775617264620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

