<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/account.proto

namespace Bluehead\V2ray\Core\Proxy\Vmess;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.vmess.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Number of alternative IDs. Client and server must share the same number.
     *
     * Generated from protobuf field <code>uint32 alter_id = 2;</code>
     */
    private $alter_id = 0;
    /**
     * Security settings. Only applies to client side.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.protocol.SecurityConfig security_settings = 3;</code>
     */
    private $security_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *     @type int $alter_id
     *           Number of alternative IDs. Client and server must share the same number.
     *     @type \Bluehead\V2ray\Core\Common\Protocol\SecurityConfig $security_settings
     *           Security settings. Only applies to client side.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Proxy\Vmess\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Number of alternative IDs. Client and server must share the same number.
     *
     * Generated from protobuf field <code>uint32 alter_id = 2;</code>
     * @return int
     */
    public function getAlterId()
    {
        return $this->alter_id;
    }

    /**
     * Number of alternative IDs. Client and server must share the same number.
     *
     * Generated from protobuf field <code>uint32 alter_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAlterId($var)
    {
        GPBUtil::checkUint32($var);
        $this->alter_id = $var;

        return $this;
    }

    /**
     * Security settings. Only applies to client side.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.protocol.SecurityConfig security_settings = 3;</code>
     * @return \Bluehead\V2ray\Core\Common\Protocol\SecurityConfig
     */
    public function getSecuritySettings()
    {
        return $this->security_settings;
    }

    /**
     * Security settings. Only applies to client side.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.protocol.SecurityConfig security_settings = 3;</code>
     * @param \Bluehead\V2ray\Core\Common\Protocol\SecurityConfig $var
     * @return $this
     */
    public function setSecuritySettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Protocol\SecurityConfig::class);
        $this->security_settings = $var;

        return $this;
    }

}

