<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Domain for routing decision. 
 *
 * Generated from protobuf message <code>bluehead.v2ray.core.app.router.Domain</code>
 */
class Domain extends \Google\Protobuf\Internal\Message
{
    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.router.Domain.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    private $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Domain matching type.
     *     @type string $value
     *           Domain value.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.router.Domain.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.router.Domain.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\App\Router\Domain_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

