<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.router.GeoIPList</code>
 */
class GeoIPList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.GeoIP entry = 1;</code>
     */
    private $entry;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\App\Router\GeoIP[]|\Google\Protobuf\Internal\RepeatedField $entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.GeoIP entry = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.GeoIP entry = 1;</code>
     * @param \Bluehead\V2ray\Core\App\Router\GeoIP[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntry($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Router\GeoIP::class);
        $this->entry = $arr;

        return $this;
    }

}

