<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.router.GeoSite</code>
 */
class GeoSite extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     */
    private $country_code = '';
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     */
    private $domain;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $country_code
     *     @type \Bluehead\V2ray\Core\App\Router\Domain[]|\Google\Protobuf\Internal\RepeatedField $domain
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Router\Domain[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Router\Domain::class);
        $this->domain = $arr;

        return $this;
    }

}

