<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.router.RoutingRule</code>
 */
class RoutingRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    private $tag = '';
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     */
    private $domain;
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR cidr = 3;</code>
     */
    private $cidr;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.PortRange port_range = 4;</code>
     */
    private $port_range = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 5;</code>
     */
    private $network_list = null;
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR source_cidr = 6;</code>
     */
    private $source_cidr;
    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     */
    private $user_email;
    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     */
    private $inbound_tag;
    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     */
    private $protocol;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type \Bluehead\V2ray\Core\App\Router\Domain[]|\Google\Protobuf\Internal\RepeatedField $domain
     *     @type \Bluehead\V2ray\Core\App\Router\CIDR[]|\Google\Protobuf\Internal\RepeatedField $cidr
     *     @type \Bluehead\V2ray\Core\Common\Net\PortRange $port_range
     *     @type \Bluehead\V2ray\Core\Common\Net\NetworkList $network_list
     *     @type \Bluehead\V2ray\Core\App\Router\CIDR[]|\Google\Protobuf\Internal\RepeatedField $source_cidr
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $user_email
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $inbound_tag
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $protocol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.Domain domain = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Router\Domain[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Router\Domain::class);
        $this->domain = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR cidr = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCidr()
    {
        return $this->cidr;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR cidr = 3;</code>
     * @param \Bluehead\V2ray\Core\App\Router\CIDR[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCidr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Router\CIDR::class);
        $this->cidr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.PortRange port_range = 4;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\PortRange
     */
    public function getPortRange()
    {
        return $this->port_range;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.PortRange port_range = 4;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\PortRange $var
     * @return $this
     */
    public function setPortRange($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\PortRange::class);
        $this->port_range = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 5;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\NetworkList
     */
    public function getNetworkList()
    {
        return $this->network_list;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 5;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\NetworkList $var
     * @return $this
     */
    public function setNetworkList($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\NetworkList::class);
        $this->network_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR source_cidr = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceCidr()
    {
        return $this->source_cidr;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.router.CIDR source_cidr = 6;</code>
     * @param \Bluehead\V2ray\Core\App\Router\CIDR[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceCidr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Router\CIDR::class);
        $this->source_cidr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserEmail()
    {
        return $this->user_email;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserEmail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_email = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInboundTag()
    {
        return $this->inbound_tag;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInboundTag($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->inbound_tag = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProtocol($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->protocol = $arr;

        return $this;
    }

}

