<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy\SystemPolicy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.SystemPolicy.Stats</code>
 */
class Stats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool inbound_uplink = 1;</code>
     */
    private $inbound_uplink = false;
    /**
     * Generated from protobuf field <code>bool inbound_downlink = 2;</code>
     */
    private $inbound_downlink = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $inbound_uplink
     *     @type bool $inbound_downlink
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool inbound_uplink = 1;</code>
     * @return bool
     */
    public function getInboundUplink()
    {
        return $this->inbound_uplink;
    }

    /**
     * Generated from protobuf field <code>bool inbound_uplink = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setInboundUplink($var)
    {
        GPBUtil::checkBool($var);
        $this->inbound_uplink = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inbound_downlink = 2;</code>
     * @return bool
     */
    public function getInboundDownlink()
    {
        return $this->inbound_downlink;
    }

    /**
     * Generated from protobuf field <code>bool inbound_downlink = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setInboundDownlink($var)
    {
        GPBUtil::checkBool($var);
        $this->inbound_downlink = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stats::class, \Bluehead\V2ray\Core\App\Policy\SystemPolicy_Stats::class);

