<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto

namespace GPBMetadata\V2ray\App\Commander;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\V2ray\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8010a1a6170702f636f6d6d616e6465722f636f6e6669672e70726f74" .
            "6f1221626c7565686561642e76327261792e636f72652e6170702e636f6d" .
            "6d616e64657222570a06436f6e666967120b0a0374616718012001280912" .
            "400a077365727669636518022003280b322f2e626c7565686561642e7632" .
            "7261792e636f72652e636f6d6d6f6e2e73657269616c2e54797065644d65" .
            "737361676542460a1c636f6d2e76327261792e636f72652e6170702e636f" .
            "6d6d616e64657250015a09636f6d6d616e646572aa021856325261792e43" .
            "6f72652e4170702e436f6d6d616e646572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

