<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Shadowsocks\Account;

/**
 * Protobuf type <code>bluehead.v2ray.core.proxy.shadowsocks.Account.OneTimeAuth</code>
 */
class OneTimeAuth
{
    /**
     * Generated from protobuf enum <code>Auto = 0;</code>
     */
    const Auto = 0;
    /**
     * Generated from protobuf enum <code>Disabled = 1;</code>
     */
    const Disabled = 1;
    /**
     * Generated from protobuf enum <code>Enabled = 2;</code>
     */
    const Enabled = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OneTimeAuth::class, \Bluehead\V2ray\Core\Proxy\Shadowsocks\Account_OneTimeAuth::class);

