<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Tls;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\Transport\Internet\Tls\Certificate\Usage instead.
     * @deprecated
     */
    class Certificate_Usage {}
}
class_exists(Certificate\Usage::class);
@trigger_error('Bluehead\V2ray\Core\Transport\Internet\Tls\Certificate_Usage is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\Transport\Internet\Tls\Certificate\Usage instead', E_USER_DEPRECATED);

