<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.tls.Certificate</code>
 */
class Certificate extends \Google\Protobuf\Internal\Message
{
    /**
     * TLS certificate in x509 format.
     *
     * Generated from protobuf field <code>bytes Certificate = 1;</code>
     */
    private $Certificate = '';
    /**
     * TLS key in x509 format.
     *
     * Generated from protobuf field <code>bytes Key = 2;</code>
     */
    private $Key = '';
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.tls.Certificate.Usage usage = 3;</code>
     */
    private $usage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Certificate
     *           TLS certificate in x509 format.
     *     @type string $Key
     *           TLS key in x509 format.
     *     @type int $usage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Tls\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * TLS certificate in x509 format.
     *
     * Generated from protobuf field <code>bytes Certificate = 1;</code>
     * @return string
     */
    public function getCertificate()
    {
        return $this->Certificate;
    }

    /**
     * TLS certificate in x509 format.
     *
     * Generated from protobuf field <code>bytes Certificate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->Certificate = $var;

        return $this;
    }

    /**
     * TLS key in x509 format.
     *
     * Generated from protobuf field <code>bytes Key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->Key;
    }

    /**
     * TLS key in x509 format.
     *
     * Generated from protobuf field <code>bytes Key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->Key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.tls.Certificate.Usage usage = 3;</code>
     * @return int
     */
    public function getUsage()
    {
        return $this->usage;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.tls.Certificate.Usage usage = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUsage($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Transport\Internet\Tls\Certificate_Usage::class);
        $this->usage = $var;

        return $this;
    }

}

