<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/outbound/config.proto

namespace GPBMetadata\V2ray\Proxy\Vmess\Outbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\V2ray\Common\Protocol\ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afb010a2170726f78792f766d6573732f6f7574626f756e642f636f6e66" .
            "69672e70726f746f1228626c7565686561642e76327261792e636f72652e" .
            "70726f78792e766d6573732e6f7574626f756e64224f0a06436f6e666967" .
            "12450a08526563656976657218012003280b32332e626c7565686561642e" .
            "76327261792e636f72652e636f6d6d6f6e2e70726f746f636f6c2e536572" .
            "766572456e64706f696e7442530a23636f6d2e76327261792e636f72652e" .
            "70726f78792e766d6573732e6f7574626f756e6450015a086f7574626f75" .
            "6e64aa021f56325261792e436f72652e50726f78792e566d6573732e4f75" .
            "74626f756e64620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

