<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Bluehead\V2ray\Core\Proxy\Freedom;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\Proxy\Freedom\Config\DomainStrategy instead.
     * @deprecated
     */
    class Config_DomainStrategy {}
}
class_exists(Config\DomainStrategy::class);
@trigger_error('Bluehead\V2ray\Core\Proxy\Freedom\Config_DomainStrategy is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\Proxy\Freedom\Config\DomainStrategy instead', E_USER_DEPRECATED);

