<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Bluehead\V2ray\Core\Proxy\Freedom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.freedom.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     */
    private $domain_strategy = 0;
    /**
     * Generated from protobuf field <code>uint32 timeout = 2 [deprecated = true];</code>
     */
    private $timeout = 0;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
     */
    private $destination_override = null;
    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     */
    private $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $domain_strategy
     *     @type int $timeout
     *     @type \Bluehead\V2ray\Core\Proxy\Freedom\DestinationOverride $destination_override
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Proxy\Freedom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     * @return int
     */
    public function getDomainStrategy()
    {
        return $this->domain_strategy;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDomainStrategy($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Proxy\Freedom\Config_DomainStrategy::class);
        $this->domain_strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 2 [deprecated = true];</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 2 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
     * @return \Bluehead\V2ray\Core\Proxy\Freedom\DestinationOverride
     */
    public function getDestinationOverride()
    {
        return $this->destination_override;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
     * @param \Bluehead\V2ray\Core\Proxy\Freedom\DestinationOverride $var
     * @return $this
     */
    public function setDestinationOverride($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Proxy\Freedom\DestinationOverride::class);
        $this->destination_override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

