<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/mtproto/config.proto

namespace Bluehead\V2ray\Core\Proxy\Mtproto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.mtproto.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * User is a list of users that allowed to connect to this inbound.
     * Although this is a repeated field, only the first user is effective for now.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 1;</code>
     */
    private $user;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Protocol\User[]|\Google\Protobuf\Internal\RepeatedField $user
     *           User is a list of users that allowed to connect to this inbound.
     *           Although this is a repeated field, only the first user is effective for now.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Proxy\Mtproto\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * User is a list of users that allowed to connect to this inbound.
     * Although this is a repeated field, only the first user is effective for now.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * User is a list of users that allowed to connect to this inbound.
     * Although this is a repeated field, only the first user is effective for now.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Protocol\User[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\Common\Protocol\User::class);
        $this->user = $arr;

        return $this;
    }

}

