<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dokodemo/config.proto

namespace Bluehead\V2ray\GPBMetadata\Proxy\Dokodemo;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Bluehead\V2ray\GPBMetadata\Common\Net\Address::initOnce();
        \Bluehead\V2ray\GPBMetadata\Common\Net\Network::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87030a1b70726f78792f646f6b6f64656d6f2f636f6e6669672e70726f" .
            "746f1222626c7565686561642e76327261792e636f72652e70726f78792e" .
            "646f6b6f64656d6f1a18636f6d6d6f6e2f6e65742f6e6574776f726b2e70" .
            "726f746f22d8010a06436f6e666967123b0a076164647265737318012001" .
            "280b322a2e626c7565686561642e76327261792e636f72652e636f6d6d6f" .
            "6e2e6e65742e49504f72446f6d61696e120c0a04706f727418022001280d" .
            "12410a0c6e6574776f726b5f6c69737418032001280b322b2e626c756568" .
            "6561642e76327261792e636f72652e636f6d6d6f6e2e6e65742e4e657477" .
            "6f726b4c69737412130a0774696d656f757418042001280d420218011217" .
            "0a0f666f6c6c6f775f726564697265637418052001280812120a0a757365" .
            "725f6c6576656c18062001280d42470a1d636f6d2e76327261792e636f72" .
            "652e70726f78792e646f6b6f64656d6f50015a08646f6b6f64656d6faa02" .
            "1956325261792e436f72652e50726f78792e446f6b6f64656d6f62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

