<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dokodemo/config.proto

namespace Bluehead\V2ray\Core\Proxy\Dokodemo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.dokodemo.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    private $port = 0;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 3;</code>
     */
    private $network_list = null;
    /**
     * Generated from protobuf field <code>uint32 timeout = 4 [deprecated = true];</code>
     */
    private $timeout = 0;
    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     */
    private $follow_redirect = false;
    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     */
    private $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Net\IPOrDomain $address
     *     @type int $port
     *     @type \Bluehead\V2ray\Core\Common\Net\NetworkList $network_list
     *     @type int $timeout
     *     @type bool $follow_redirect
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Proxy\Dokodemo\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\IPOrDomain
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 3;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\NetworkList
     */
    public function getNetworkList()
    {
        return $this->network_list;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.NetworkList network_list = 3;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\NetworkList $var
     * @return $this
     */
    public function setNetworkList($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\NetworkList::class);
        $this->network_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 4 [deprecated = true];</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 4 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @return bool
     */
    public function getFollowRedirect()
    {
        return $this->follow_redirect;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFollowRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->follow_redirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

