<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/command/config.proto

namespace Bluehead\V2ray\Core\App\Log\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.log.command.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Log\Command\Config::initOnce();
        parent::__construct($data);
    }

}

