<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency instead.
     * @deprecated
     */
    class AllocationStrategy_AllocationStrategyConcurrency {}
}
class_exists(AllocationStrategy\AllocationStrategyConcurrency::class);
@trigger_error('Bluehead\V2ray\Core\App\Proxyman\AllocationStrategy_AllocationStrategyConcurrency is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Proxyman\AllocationStrategy\AllocationStrategyConcurrency instead', E_USER_DEPRECATED);

