<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.InboundHandlerConfig</code>
 */
class InboundHandlerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    private $tag = '';
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
     */
    private $receiver_settings = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    private $proxy_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage $receiver_settings
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage $proxy_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
     * @return \Bluehead\V2ray\Core\Common\Serial\TypedMessage
     */
    public function getReceiverSettings()
    {
        return $this->receiver_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setReceiverSettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->receiver_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     * @return \Bluehead\V2ray\Core\Common\Serial\TypedMessage
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->proxy_settings = $var;

        return $this;
    }

}

