<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

/**
 * Protobuf type <code>bluehead.v2ray.core.app.proxyman.KnownProtocols</code>
 */
class KnownProtocols
{
    /**
     * Generated from protobuf enum <code>HTTP = 0;</code>
     */
    const HTTP = 0;
    /**
     * Generated from protobuf enum <code>TLS = 1;</code>
     */
    const TLS = 1;
}

