<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.MultiplexingConfig</code>
 */
class MultiplexingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    private $enabled = false;
    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>uint32 concurrency = 2;</code>
     */
    private $concurrency = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Whether or not Mux is enabled.
     *     @type int $concurrency
     *           Max number of concurrent connections that one Mux connection can handle.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Whether or not Mux is enabled.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>uint32 concurrency = 2;</code>
     * @return int
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    /**
     * Max number of concurrent connections that one Mux connection can handle.
     *
     * Generated from protobuf field <code>uint32 concurrency = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkUint32($var);
        $this->concurrency = $var;

        return $this;
    }

}

