<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.SenderConfig</code>
 */
class SenderConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain via = 1;</code>
     */
    private $via = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    private $stream_settings = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    private $proxy_settings = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    private $multiplex_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Net\IPOrDomain $via
     *           Send traffic through the given IP. Only IP is allowed.
     *     @type \Bluehead\V2ray\Core\Transport\Internet\StreamConfig $stream_settings
     *     @type \Bluehead\V2ray\Core\Transport\Internet\ProxyConfig $proxy_settings
     *     @type \Bluehead\V2ray\Core\App\Proxyman\MultiplexingConfig $multiplex_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain via = 1;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\IPOrDomain
     */
    public function getVia()
    {
        return $this->via;
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain via = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setVia($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\IPOrDomain::class);
        $this->via = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return \Bluehead\V2ray\Core\Transport\Internet\StreamConfig
     */
    public function getStreamSettings()
    {
        return $this->stream_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     * @param \Bluehead\V2ray\Core\Transport\Internet\StreamConfig $var
     * @return $this
     */
    public function setStreamSettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Transport\Internet\StreamConfig::class);
        $this->stream_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return \Bluehead\V2ray\Core\Transport\Internet\ProxyConfig
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @param \Bluehead\V2ray\Core\Transport\Internet\ProxyConfig $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Transport\Internet\ProxyConfig::class);
        $this->proxy_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return \Bluehead\V2ray\Core\App\Proxyman\MultiplexingConfig
     */
    public function getMultiplexSettings()
    {
        return $this->multiplex_settings;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @param \Bluehead\V2ray\Core\App\Proxyman\MultiplexingConfig $var
     * @return $this
     */
    public function setMultiplexSettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Proxyman\MultiplexingConfig::class);
        $this->multiplex_settings = $var;

        return $this;
    }

}

