<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/config.proto

namespace Bluehead\V2ray\Core\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.proxyman.SniffingConfig</code>
 */
class SniffingConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    private $enabled = false;
    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     */
    private $destination_override;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *           Whether or not to enable content sniffing on an inbound connection.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $destination_override
     *           Override target destination if sniff'ed protocol is in the given list.
     *           Supported values are "http", "tls".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Whether or not to enable content sniffing on an inbound connection.
     *
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDestinationOverride()
    {
        return $this->destination_override;
    }

    /**
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     *
     * Generated from protobuf field <code>repeated string destination_override = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDestinationOverride($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->destination_override = $arr;

        return $this;
    }

}

