<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Shadowsocks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.shadowsocks.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string password = 1;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     */
    private $cipher_type = 0;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     */
    private $ota = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $password
     *     @type int $cipher_type
     *     @type int $ota
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Proxy\Shadowsocks\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     * @return int
     */
    public function getCipherType()
    {
        return $this->cipher_type;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCipherType($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Proxy\Shadowsocks\CipherType::class);
        $this->cipher_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     * @return int
     */
    public function getOta()
    {
        return $this->ota;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOta($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Proxy\Shadowsocks\Account_OneTimeAuth::class);
        $this->ota = $var;

        return $this;
    }

}

