<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Shadowsocks;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\Proxy\Shadowsocks\Account\OneTimeAuth instead.
     * @deprecated
     */
    class Account_OneTimeAuth {}
}
class_exists(Account\OneTimeAuth::class);
@trigger_error('Bluehead\V2ray\Core\Proxy\Shadowsocks\Account_OneTimeAuth is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\Proxy\Shadowsocks\Account\OneTimeAuth instead', E_USER_DEPRECATED);

