<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Shadowsocks;

/**
 * Protobuf type <code>bluehead.v2ray.core.proxy.shadowsocks.CipherType</code>
 */
class CipherType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>AES_128_CFB = 1;</code>
     */
    const AES_128_CFB = 1;
    /**
     * Generated from protobuf enum <code>AES_256_CFB = 2;</code>
     */
    const AES_256_CFB = 2;
    /**
     * Generated from protobuf enum <code>CHACHA20 = 3;</code>
     */
    const CHACHA20 = 3;
    /**
     * Generated from protobuf enum <code>CHACHA20_IETF = 4;</code>
     */
    const CHACHA20_IETF = 4;
    /**
     * Generated from protobuf enum <code>AES_128_GCM = 5;</code>
     */
    const AES_128_GCM = 5;
    /**
     * Generated from protobuf enum <code>AES_256_GCM = 6;</code>
     */
    const AES_256_GCM = 6;
    /**
     * Generated from protobuf enum <code>CHACHA20_POLY1305 = 7;</code>
     */
    const CHACHA20_POLY1305 = 7;
    /**
     * Generated from protobuf enum <code>NONE = 8;</code>
     */
    const NONE = 8;
}

