<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/noop/config.proto

namespace GPBMetadata\V2ray\Transport\Internet\Headers\Noop;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0010a2c7472616e73706f72742f696e7465726e65742f686561646572" .
            "732f6e6f6f702f636f6e6669672e70726f746f1233626c7565686561642e" .
            "76327261792e636f72652e7472616e73706f72742e696e7465726e65742e" .
            "686561646572732e6e6f6f7022080a06436f6e66696722120a10436f6e6e" .
            "656374696f6e436f6e66696742650a2e636f6d2e76327261792e636f7265" .
            "2e7472616e73706f72742e696e7465726e65742e686561646572732e6e6f" .
            "6f7050015a046e6f6f70aa022a56325261792e436f72652e5472616e7370" .
            "6f72742e496e7465726e65742e486561646572732e4e6f6f70620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

