<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/blackhole/config.proto

namespace Bluehead\V2ray\GPBMetadata\Proxy\Blackhole;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Bluehead\V2ray\GPBMetadata\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a1c70726f78792f626c61636b686f6c652f636f6e6669672e7072" .
            "6f746f1223626c7565686561642e76327261792e636f72652e70726f7879" .
            "2e626c61636b686f6c65220e0a0c4e6f6e65526573706f6e7365220e0a0c" .
            "48545450526573706f6e7365224b0a06436f6e66696712410a0872657370" .
            "6f6e736518012001280b322f2e626c7565686561642e76327261792e636f" .
            "72652e636f6d6d6f6e2e73657269616c2e54797065644d65737361676542" .
            "4a0a1e636f6d2e76327261792e636f72652e70726f78792e626c61636b68" .
            "6f6c6550015a09626c61636b686f6c65aa021a56325261792e436f72652e" .
            "50726f78792e426c61636b686f6c65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

