<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\SocketConfig;

/**
 * Protobuf type <code>bluehead.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState</code>
 */
class TCPFastOpenState
{
    /**
     * AsIs is to leave the current TFO state as is, unmodified.
     *
     * Generated from protobuf enum <code>AsIs = 0;</code>
     */
    const AsIs = 0;
    /**
     * Enable is for enabling TFO explictly.
     *
     * Generated from protobuf enum <code>Enable = 1;</code>
     */
    const Enable = 1;
    /**
     * Disable is for disabling TFO explictly.
     *
     * Generated from protobuf enum <code>Disable = 2;</code>
     */
    const Disable = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TCPFastOpenState::class, \Bluehead\V2ray\Core\Transport\Internet\SocketConfig_TCPFastOpenState::class);

