<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet\SocketConfig;

/**
 * Protobuf type <code>bluehead.v2ray.core.transport.internet.SocketConfig.TProxyMode</code>
 */
class TProxyMode
{
    /**
     * TProxy is off.
     *
     * Generated from protobuf enum <code>Off = 0;</code>
     */
    const Off = 0;
    /**
     * TProxy mode.
     *
     * Generated from protobuf enum <code>TProxy = 1;</code>
     */
    const TProxy = 1;
    /**
     * Redirect mode.
     *
     * Generated from protobuf enum <code>Redirect = 2;</code>
     */
    const Redirect = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TProxyMode::class, \Bluehead\V2ray\Core\Transport\Internet\SocketConfig_TProxyMode::class);

