<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Bluehead\V2ray\Core\Proxy\Freedom\Config;

/**
 * Protobuf type <code>bluehead.v2ray.core.proxy.freedom.Config.DomainStrategy</code>
 */
class DomainStrategy
{
    /**
     * Generated from protobuf enum <code>AS_IS = 0;</code>
     */
    const AS_IS = 0;
    /**
     * Generated from protobuf enum <code>USE_IP = 1;</code>
     */
    const USE_IP = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DomainStrategy::class, \Bluehead\V2ray\Core\Proxy\Freedom\Config_DomainStrategy::class);

