<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/address.proto

namespace Bluehead\V2ray\Core\Common\Net;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Address of a network host. It may be either an IP address or a domain address.
 *
 * Generated from protobuf message <code>bluehead.v2ray.core.common.net.IPOrDomain</code>
 */
class IPOrDomain extends \Google\Protobuf\Internal\Message
{
    protected $address;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip
     *           IP address. Must by either 4 or 16 bytes.
     *     @type string $domain
     *           Domain address.
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Common\Net\Address::initOnce();
        parent::__construct($data);
    }

    /**
     * IP address. Must by either 4 or 16 bytes.
     *
     * Generated from protobuf field <code>bytes ip = 1;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->readOneof(1);
    }

    /**
     * IP address. Must by either 4 or 16 bytes.
     *
     * Generated from protobuf field <code>bytes ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Domain address.
     *
     * Generated from protobuf field <code>string domain = 2;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->readOneof(2);
    }

    /**
     * Domain address.
     *
     * Generated from protobuf field <code>string domain = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->whichOneof("address");
    }

}

