<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/network.proto

namespace Bluehead\V2ray\Core\Common\Net;

/**
 * Protobuf type <code>bluehead.v2ray.core.common.net.Network</code>
 */
class Network
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>RawTCP = 1 [deprecated = true];</code>
     */
    const RawTCP = 1;
    /**
     * Generated from protobuf enum <code>TCP = 2;</code>
     */
    const TCP = 2;
    /**
     * Generated from protobuf enum <code>UDP = 3;</code>
     */
    const UDP = 3;
}

