<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/udp/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Udp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a237472616e73706f72742f696e7465726e65742f7564702f636f" .
            "6e6669672e70726f746f122a626c7565686561642e76327261792e636f72" .
            "652e7472616e73706f72742e696e7465726e65742e75647022080a06436f" .
            "6e66696742520a25636f6d2e76327261792e636f72652e7472616e73706f" .
            "72742e696e7465726e65742e75647050015a03756470aa02215632526179" .
            "2e436f72652e5472616e73706f72742e496e7465726e65742e5564706206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

