<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/log/log.proto

namespace Bluehead\V2ray\Core\Common\Log;

/**
 * Protobuf type <code>bluehead.v2ray.core.common.log.Severity</code>
 */
class Severity
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Error = 1;</code>
     */
    const Error = 1;
    /**
     * Generated from protobuf enum <code>Warning = 2;</code>
     */
    const Warning = 2;
    /**
     * Generated from protobuf enum <code>Info = 3;</code>
     */
    const Info = 3;
    /**
     * Generated from protobuf enum <code>Debug = 4;</code>
     */
    const Debug = 4;
}

