<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<uint32, .bluehead.v2ray.core.app.policy.Policy> level = 1;</code>
     */
    private $level;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy system = 2;</code>
     */
    private $system = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $level
     *     @type \Bluehead\V2ray\Core\App\Policy\SystemPolicy $system
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<uint32, .bluehead.v2ray.core.app.policy.Policy> level = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .bluehead.v2ray.core.app.policy.Policy> level = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLevel($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Policy\Policy::class);
        $this->level = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy system = 2;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\SystemPolicy
     */
    public function getSystem()
    {
        return $this->system;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy system = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\SystemPolicy $var
     * @return $this
     */
    public function setSystem($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\SystemPolicy::class);
        $this->system = $var;

        return $this;
    }

}

