<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Policy\Policy\Buffer instead.
     * @deprecated
     */
    class Policy_Buffer {}
}
class_exists(Policy\Buffer::class);
@trigger_error('Bluehead\V2ray\Core\App\Policy\Policy_Buffer is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Policy\Policy\Buffer instead', E_USER_DEPRECATED);

