<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.Policy</code>
 */
class Policy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     */
    private $timeout = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     */
    private $stats = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     */
    private $buffer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\App\Policy\Policy\Timeout $timeout
     *     @type \Bluehead\V2ray\Core\App\Policy\Policy\Stats $stats
     *     @type \Bluehead\V2ray\Core\App\Policy\Policy\Buffer $buffer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Policy\Timeout
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Policy\Timeout $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Policy_Timeout::class);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Policy\Stats
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Policy\Stats $var
     * @return $this
     */
    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Policy_Stats::class);
        $this->stats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Policy\Buffer
     */
    public function getBuffer()
    {
        return $this->buffer;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Policy\Buffer $var
     * @return $this
     */
    public function setBuffer($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Policy_Buffer::class);
        $this->buffer = $var;

        return $this;
    }

}

