<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Policy\Policy\Timeout instead.
     * @deprecated
     */
    class Policy_Timeout {}
}
class_exists(Policy\Timeout::class);
@trigger_error('Bluehead\V2ray\Core\App\Policy\Policy_Timeout is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Policy\Policy\Timeout instead', E_USER_DEPRECATED);

