<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.SystemPolicy</code>
 */
class SystemPolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     */
    private $stats = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\App\Policy\SystemPolicy\Stats $stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\SystemPolicy\Stats
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\SystemPolicy\Stats $var
     * @return $this
     */
    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\SystemPolicy_Stats::class);
        $this->stats = $var;

        return $this;
    }

}

