<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Policy\SystemPolicy\Stats instead.
     * @deprecated
     */
    class SystemPolicy_Stats {}
}
class_exists(SystemPolicy\Stats::class);
@trigger_error('Bluehead\V2ray\Core\App\Policy\SystemPolicy_Stats is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Policy\SystemPolicy\Stats instead', E_USER_DEPRECATED);

