<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Bluehead\V2ray\Core\App\Dns;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Dns\Config\HostMapping instead.
     * @deprecated
     */
    class Config_HostMapping {}
}
class_exists(Config\HostMapping::class);
@trigger_error('Bluehead\V2ray\Core\App\Dns\Config_HostMapping is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Dns\Config\HostMapping instead', E_USER_DEPRECATED);

