<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Bluehead\V2ray\Core\App\Dns;

/**
 * Protobuf type <code>bluehead.v2ray.core.app.dns.DomainMatchingType</code>
 */
class DomainMatchingType
{
    /**
     * Generated from protobuf enum <code>Full = 0;</code>
     */
    const Full = 0;
    /**
     * Generated from protobuf enum <code>Subdomain = 1;</code>
     */
    const Subdomain = 1;
    /**
     * Generated from protobuf enum <code>Keyword = 2;</code>
     */
    const Keyword = 2;
    /**
     * Generated from protobuf enum <code>Regex = 3;</code>
     */
    const Regex = 3;
}

