<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Bluehead\V2ray\Core\App\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.dns.NameServer</code>
 */
class NameServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.Endpoint address = 1;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     */
    private $prioritized_domain;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Net\Endpoint $address
     *     @type \Bluehead\V2ray\Core\App\Dns\NameServer\PriorityDomain[]|\Google\Protobuf\Internal\RepeatedField $prioritized_domain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.Endpoint address = 1;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\Endpoint
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.Endpoint address = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\Endpoint $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\Endpoint::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrioritizedDomain()
    {
        return $this->prioritized_domain;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.app.dns.NameServer.PriorityDomain prioritized_domain = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Dns\NameServer\PriorityDomain[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrioritizedDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\App\Dns\NameServer\PriorityDomain::class);
        $this->prioritized_domain = $arr;

        return $this;
    }

}

