<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Bluehead\V2ray\Core\App\Dns;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\App\Dns\NameServer\PriorityDomain instead.
     * @deprecated
     */
    class NameServer_PriorityDomain {}
}
class_exists(NameServer\PriorityDomain::class);
@trigger_error('Bluehead\V2ray\Core\App\Dns\NameServer_PriorityDomain is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\App\Dns\NameServer\PriorityDomain instead', E_USER_DEPRECATED);

