<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/tls/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Tls;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add010a2b7472616e73706f72742f696e7465726e65742f686561646572" .
            "732f746c732f636f6e6669672e70726f746f1232626c7565686561642e76" .
            "327261792e636f72652e7472616e73706f72742e696e7465726e65742e68" .
            "6561646572732e746c73220e0a0c5061636b6574436f6e66696742620a2d" .
            "636f6d2e76327261792e636f72652e7472616e73706f72742e696e746572" .
            "6e65742e686561646572732e746c7350015a03746c73aa02295632526179" .
            "2e436f72652e5472616e73706f72742e496e7465726e65742e4865616465" .
            "72732e546c73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

