<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/headers.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Protocol;

class Headers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace020a1d636f6d6d6f6e2f70726f746f636f6c2f686561646572732e70" .
            "726f746f1223626c7565686561642e76327261792e636f72652e636f6d6d" .
            "6f6e2e70726f746f636f6c22510a0e5365637572697479436f6e66696712" .
            "3f0a047479706518012001280e32312e626c7565686561642e7632726179" .
            "2e636f72652e636f6d6d6f6e2e70726f746f636f6c2e5365637572697479" .
            "547970652a620a0c536563757269747954797065120b0a07554e4b4e4f57" .
            "4e1000120a0a064c4547414359100112080a044155544f1002120e0a0a41" .
            "45533132385f47434d100312150a1143484143484132305f504f4c593133" .
            "3035100412080a044e4f4e45100542490a1e636f6d2e76327261792e636f" .
            "72652e636f6d6d6f6e2e70726f746f636f6c50015a0870726f746f636f6c" .
            "aa021a56325261792e436f72652e436f6d6d6f6e2e50726f746f636f6c62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

