<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/server_spec.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Protocol;

class ServerSpec
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Bluehead\V2ray\GPBMetadata\Common\Net\Address::initOnce();
        \Bluehead\V2ray\GPBMetadata\Common\Protocol\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace020a21636f6d6d6f6e2f70726f746f636f6c2f7365727665725f7370" .
            "65632e70726f746f1223626c7565686561642e76327261792e636f72652e" .
            "636f6d6d6f6e2e70726f746f636f6c1a1a636f6d6d6f6e2f70726f746f63" .
            "6f6c2f757365722e70726f746f2294010a0e536572766572456e64706f69" .
            "6e74123b0a076164647265737318012001280b322a2e626c756568656164" .
            "2e76327261792e636f72652e636f6d6d6f6e2e6e65742e49504f72446f6d" .
            "61696e120c0a04706f727418022001280d12370a04757365721803200328" .
            "0b32292e626c7565686561642e76327261792e636f72652e636f6d6d6f6e" .
            "2e70726f746f636f6c2e5573657242490a1e636f6d2e76327261792e636f" .
            "72652e636f6d6d6f6e2e70726f746f636f6c50015a0870726f746f636f6c" .
            "aa021a56325261792e436f72652e436f6d6d6f6e2e50726f746f636f6c62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

