<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\Transport\Internet\SocketConfig\TCPFastOpenState instead.
     * @deprecated
     */
    class SocketConfig_TCPFastOpenState {}
}
class_exists(SocketConfig\TCPFastOpenState::class);
@trigger_error('Bluehead\V2ray\Core\Transport\Internet\SocketConfig_TCPFastOpenState is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\Transport\Internet\SocketConfig\TCPFastOpenState instead', E_USER_DEPRECATED);

