<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet;

if (false) {
    /**
     * This class is deprecated. Use Bluehead\V2ray\Core\Transport\Internet\SocketConfig\TProxyMode instead.
     * @deprecated
     */
    class SocketConfig_TProxyMode {}
}
class_exists(SocketConfig\TProxyMode::class);
@trigger_error('Bluehead\V2ray\Core\Transport\Internet\SocketConfig_TProxyMode is deprecated and will be removed in the next major release. Use Bluehead\V2ray\Core\Transport\Internet\SocketConfig\TProxyMode instead', E_USER_DEPRECATED);

