<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.transport.internet.TransportConfig</code>
 */
class TransportConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.TransportProtocol protocol = 1;</code>
     */
    private $protocol = 0;
    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     */
    private $protocol_name = '';
    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    private $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol
     *           Type of network that this settings supports.
     *           Deprecated. Use the string form below.
     *     @type string $protocol_name
     *           Type of network that this settings supports.
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage $settings
     *           Specific settings. Must be of the transports.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.TransportProtocol protocol = 1;</code>
     * @return int
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.transport.internet.TransportProtocol protocol = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Transport\Internet\TransportProtocol::class);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     * @return string
     */
    public function getProtocolName()
    {
        return $this->protocol_name;
    }

    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol_name = $var;

        return $this;
    }

    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage settings = 2;</code>
     * @return \Bluehead\V2ray\Core\Common\Serial\TypedMessage
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.serial.TypedMessage settings = 2;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->settings = $var;

        return $this;
    }

}

