<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Bluehead\V2ray\Core\Transport\Internet;

/**
 * Protobuf type <code>bluehead.v2ray.core.transport.internet.TransportProtocol</code>
 */
class TransportProtocol
{
    /**
     * Generated from protobuf enum <code>TCP = 0;</code>
     */
    const TCP = 0;
    /**
     * Generated from protobuf enum <code>UDP = 1;</code>
     */
    const UDP = 1;
    /**
     * Generated from protobuf enum <code>MKCP = 2;</code>
     */
    const MKCP = 2;
    /**
     * Generated from protobuf enum <code>WebSocket = 3;</code>
     */
    const WebSocket = 3;
    /**
     * Generated from protobuf enum <code>HTTP = 4;</code>
     */
    const HTTP = 4;
    /**
     * Generated from protobuf enum <code>DomainSocket = 5;</code>
     */
    const DomainSocket = 5;
}

