<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/http/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8010a247472616e73706f72742f696e7465726e65742f687474702f63" .
            "6f6e6669672e70726f746f122b626c7565686561642e76327261792e636f" .
            "72652e7472616e73706f72742e696e7465726e65742e6874747022240a06" .
            "436f6e666967120c0a04686f7374180120032809120c0a04706174681802" .
            "2001280942550a26636f6d2e76327261792e636f72652e7472616e73706f" .
            "72742e696e7465726e65742e6874747050015a0468747470aa0222563252" .
            "61792e436f72652e5472616e73706f72742e496e7465726e65742e487474" .
            "70620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

