<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/wechat/config.proto

namespace GPBMetadata\V2ray\Transport\Internet\Headers\Wechat;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aeb010a2e7472616e73706f72742f696e7465726e65742f686561646572" .
            "732f7765636861742f636f6e6669672e70726f746f1235626c7565686561" .
            "642e76327261792e636f72652e7472616e73706f72742e696e7465726e65" .
            "742e686561646572732e776563686174220d0a0b566964656f436f6e6669" .
            "67426b0a30636f6d2e76327261792e636f72652e7472616e73706f72742e" .
            "696e7465726e65742e686561646572732e77656368617450015a06776563" .
            "686174aa022c56325261792e436f72652e5472616e73706f72742e496e74" .
            "65726e65742e486561646572732e576563686174620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

