<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/config.proto

namespace Bluehead\V2ray\GPBMetadata\App\Stats;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85010a166170702f73746174732f636f6e6669672e70726f746f121d62" .
            "6c7565686561642e76327261792e636f72652e6170702e73746174732208" .
            "0a06436f6e666967423a0a18636f6d2e76327261792e636f72652e617070" .
            "2e737461747350015a057374617473aa021456325261792e436f72652e41" .
            "70702e5374617473620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

