<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/http/config.proto

namespace Bluehead\V2ray\GPBMetadata\Proxy\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2020a1770726f78792f687474702f636f6e6669672e70726f746f121e" .
            "626c7565686561642e76327261792e636f72652e70726f78792e68747470" .
            "22d1010a0c536572766572436f6e66696712130a0774696d656f75741801" .
            "2001280d42021801124c0a086163636f756e747318022003280b323a2e62" .
            "6c7565686561642e76327261792e636f72652e70726f78792e687474702e" .
            "536572766572436f6e6669672e4163636f756e7473456e74727912190a11" .
            "616c6c6f775f7472616e73706172656e7418032001280812120a0a757365" .
            "725f6c6576656c18042001280d1a2f0a0d4163636f756e7473456e747279" .
            "120b0a036b6579180120012809120d0a0576616c75651802200128093a02" .
            "3801220e0a0c436c69656e74436f6e666967423b0a19636f6d2e76327261" .
            "792e636f72652e70726f78792e6874747050015a0468747470aa02155632" .
            "5261792e436f72652e50726f78792e48747470620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

