<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/utp/config.proto

namespace Bluehead\V2ray\GPBMetadata\Transport\Internet\Headers\Utp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8010a2b7472616e73706f72742f696e7465726e65742f686561646572" .
            "732f7574702f636f6e6669672e70726f746f1232626c7565686561642e76" .
            "327261792e636f72652e7472616e73706f72742e696e7465726e65742e68" .
            "6561646572732e75747022190a06436f6e666967120f0a0776657273696f" .
            "6e18012001280d42620a2d636f6d2e76327261792e636f72652e7472616e" .
            "73706f72742e696e7465726e65742e686561646572732e75747050015a03" .
            "757470aa022956325261792e436f72652e5472616e73706f72742e496e74" .
            "65726e65742e486561646572732e557470620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

