<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/headers.proto

namespace Bluehead\V2ray\Core\Common\Protocol;

/**
 * Protobuf type <code>bluehead.v2ray.core.common.protocol.SecurityType</code>
 */
class SecurityType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>LEGACY = 1;</code>
     */
    const LEGACY = 1;
    /**
     * Generated from protobuf enum <code>AUTO = 2;</code>
     */
    const AUTO = 2;
    /**
     * Generated from protobuf enum <code>AES128_GCM = 3;</code>
     */
    const AES128_GCM = 3;
    /**
     * Generated from protobuf enum <code>CHACHA20_POLY1305 = 4;</code>
     */
    const CHACHA20_POLY1305 = 4;
    /**
     * Generated from protobuf enum <code>NONE = 5;</code>
     */
    const NONE = 5;
}

