<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/server_spec.proto

namespace Bluehead\V2ray\Core\Common\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.common.protocol.ServerEndpoint</code>
 */
class ServerEndpoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    private $port = 0;
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 3;</code>
     */
    private $user;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Net\IPOrDomain $address
     *     @type int $port
     *     @type \Bluehead\V2ray\Core\Common\Protocol\User[]|\Google\Protobuf\Internal\RepeatedField $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Common\Protocol\ServerSpec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\IPOrDomain
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.User user = 3;</code>
     * @param \Bluehead\V2ray\Core\Common\Protocol\User[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\Common\Protocol\User::class);
        $this->user = $arr;

        return $this;
    }

}

