<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router\Domain;

/**
 * Type of domain value.
 *
 * Protobuf type <code>bluehead.v2ray.core.app.router.Domain.Type</code>
 */
class Type
{
    /**
     * The value is used as is.
     *
     * Generated from protobuf enum <code>Plain = 0;</code>
     */
    const Plain = 0;
    /**
     * The value is used as a regular expression.
     *
     * Generated from protobuf enum <code>Regex = 1;</code>
     */
    const Regex = 1;
    /**
     * The value is a root domain.
     *
     * Generated from protobuf enum <code>Domain = 2;</code>
     */
    const Domain = 2;
    /**
     * The value is a domain.
     *
     * Generated from protobuf enum <code>Full = 3;</code>
     */
    const Full = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Bluehead\V2ray\Core\App\Router\Domain_Type::class);

