<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/account.proto

namespace Bluehead\V2ray\GPBMetadata\Proxy\Vmess;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Bluehead\V2ray\GPBMetadata\Common\Protocol\Headers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afd010a1970726f78792f766d6573732f6163636f756e742e70726f746f" .
            "121f626c7565686561642e76327261792e636f72652e70726f78792e766d" .
            "65737322770a074163636f756e74120a0a02696418012001280912100a08" .
            "616c7465725f696418022001280d124e0a1173656375726974795f736574" .
            "74696e677318032001280b32332e626c7565686561642e76327261792e63" .
            "6f72652e636f6d6d6f6e2e70726f746f636f6c2e5365637572697479436f" .
            "6e666967423e0a1a636f6d2e76327261792e636f72652e70726f78792e76" .
            "6d65737350015a05766d657373aa021656325261792e436f72652e50726f" .
            "78792e566d657373620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

