<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.Policy.Stats</code>
 */
class Stats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     */
    private $user_uplink = false;
    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     */
    private $user_downlink = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $user_uplink
     *     @type bool $user_downlink
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     * @return bool
     */
    public function getUserUplink()
    {
        return $this->user_uplink;
    }

    /**
     * Generated from protobuf field <code>bool user_uplink = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setUserUplink($var)
    {
        GPBUtil::checkBool($var);
        $this->user_uplink = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     * @return bool
     */
    public function getUserDownlink()
    {
        return $this->user_downlink;
    }

    /**
     * Generated from protobuf field <code>bool user_downlink = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUserDownlink($var)
    {
        GPBUtil::checkBool($var);
        $this->user_downlink = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stats::class, \Bluehead\V2ray\Core\App\Policy\Policy_Stats::class);

