<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/policy/config.proto

namespace Bluehead\V2ray\Core\App\Policy\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Timeout is a message for timeout settings in various stages, in seconds.
 *
 * Generated from protobuf message <code>bluehead.v2ray.core.app.policy.Policy.Timeout</code>
 */
class Timeout extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second handshake = 1;</code>
     */
    private $handshake = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second connection_idle = 2;</code>
     */
    private $connection_idle = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second uplink_only = 3;</code>
     */
    private $uplink_only = null;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second downlink_only = 4;</code>
     */
    private $downlink_only = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\App\Policy\Second $handshake
     *     @type \Bluehead\V2ray\Core\App\Policy\Second $connection_idle
     *     @type \Bluehead\V2ray\Core\App\Policy\Second $uplink_only
     *     @type \Bluehead\V2ray\Core\App\Policy\Second $downlink_only
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second handshake = 1;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Second
     */
    public function getHandshake()
    {
        return $this->handshake;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second handshake = 1;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Second $var
     * @return $this
     */
    public function setHandshake($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Second::class);
        $this->handshake = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second connection_idle = 2;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Second
     */
    public function getConnectionIdle()
    {
        return $this->connection_idle;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second connection_idle = 2;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Second $var
     * @return $this
     */
    public function setConnectionIdle($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Second::class);
        $this->connection_idle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second uplink_only = 3;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Second
     */
    public function getUplinkOnly()
    {
        return $this->uplink_only;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second uplink_only = 3;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Second $var
     * @return $this
     */
    public function setUplinkOnly($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Second::class);
        $this->uplink_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second downlink_only = 4;</code>
     * @return \Bluehead\V2ray\Core\App\Policy\Second
     */
    public function getDownlinkOnly()
    {
        return $this->downlink_only;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.policy.Second downlink_only = 4;</code>
     * @param \Bluehead\V2ray\Core\App\Policy\Second $var
     * @return $this
     */
    public function setDownlinkOnly($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\App\Policy\Second::class);
        $this->downlink_only = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Timeout::class, \Bluehead\V2ray\Core\App\Policy\Policy_Timeout::class);

