<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto

namespace Bluehead\V2ray\Core\App\Commander;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Config is the settings for Commander.
 *
 * Generated from protobuf message <code>bluehead.v2ray.core.app.commander.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    private $tag = '';
    /**
     * Services that supported by this server. All services must implement Service interface.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.serial.TypedMessage service = 2;</code>
     */
    private $service;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *           Tag of the outbound handler that handles grpc connections.
     *     @type \Bluehead\V2ray\Core\Common\Serial\TypedMessage[]|\Google\Protobuf\Internal\RepeatedField $service
     *           Services that supported by this server. All services must implement Service interface.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Commander\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Tag of the outbound handler that handles grpc connections.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Services that supported by this server. All services must implement Service interface.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.serial.TypedMessage service = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Services that supported by this server. All services must implement Service interface.
     *
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.serial.TypedMessage service = 2;</code>
     * @param \Bluehead\V2ray\Core\Common\Serial\TypedMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\Common\Serial\TypedMessage::class);
        $this->service = $arr;

        return $this;
    }

}

