<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/domainsocket/config.proto

namespace GPBMetadata\V2ray\Transport\Internet\Domainsocket;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a2c7472616e73706f72742f696e7465726e65742f646f6d61696e" .
            "736f636b65742f636f6e6669672e70726f746f1233626c7565686561642e" .
            "76327261792e636f72652e7472616e73706f72742e696e7465726e65742e" .
            "646f6d61696e736f636b657422280a06436f6e666967120c0a0470617468" .
            "18012001280912100a086162737472616374180220012808426d0a2e636f" .
            "6d2e76327261792e636f72652e7472616e73706f72742e696e7465726e65" .
            "742e646f6d61696e736f636b657450015a0c646f6d61696e736f636b6574" .
            "aa022a56325261792e436f72652e5472616e73706f72742e496e7465726e" .
            "65742e446f6d61696e536f636b6574620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

