<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/serial/typed_message.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Serial;

class TypedMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a21636f6d6d6f6e2f73657269616c2f74797065645f6d65737361" .
            "67652e70726f746f1221626c7565686561642e76327261792e636f72652e" .
            "636f6d6d6f6e2e73657269616c222b0a0c54797065644d65737361676512" .
            "0c0a0474797065180120012809120d0a0576616c756518022001280c4243" .
            "0a1c636f6d2e76327261792e636f72652e636f6d6d6f6e2e73657269616c" .
            "50015a0673657269616caa021856325261792e436f72652e436f6d6d6f6e" .
            "2e53657269616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

