<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/config.proto

namespace Bluehead\V2ray\Core\App\Log;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.app.log.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType error_log_type = 1;</code>
     */
    private $error_log_type = 0;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.log.Severity error_log_level = 2;</code>
     */
    private $error_log_level = 0;
    /**
     * Generated from protobuf field <code>string error_log_path = 3;</code>
     */
    private $error_log_path = '';
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType access_log_type = 4;</code>
     */
    private $access_log_type = 0;
    /**
     * Generated from protobuf field <code>string access_log_path = 5;</code>
     */
    private $access_log_path = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_log_type
     *     @type int $error_log_level
     *     @type string $error_log_path
     *     @type int $access_log_type
     *     @type string $access_log_path
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Log\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType error_log_type = 1;</code>
     * @return int
     */
    public function getErrorLogType()
    {
        return $this->error_log_type;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType error_log_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorLogType($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\App\Log\LogType::class);
        $this->error_log_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.log.Severity error_log_level = 2;</code>
     * @return int
     */
    public function getErrorLogLevel()
    {
        return $this->error_log_level;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.log.Severity error_log_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorLogLevel($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Common\Log\Severity::class);
        $this->error_log_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_log_path = 3;</code>
     * @return string
     */
    public function getErrorLogPath()
    {
        return $this->error_log_path;
    }

    /**
     * Generated from protobuf field <code>string error_log_path = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorLogPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_log_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType access_log_type = 4;</code>
     * @return int
     */
    public function getAccessLogType()
    {
        return $this->access_log_type;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.app.log.LogType access_log_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAccessLogType($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\App\Log\LogType::class);
        $this->access_log_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_log_path = 5;</code>
     * @return string
     */
    public function getAccessLogPath()
    {
        return $this->access_log_path;
    }

    /**
     * Generated from protobuf field <code>string access_log_path = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessLogPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_log_path = $var;

        return $this;
    }

}

