<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/config.proto

namespace Bluehead\V2ray\Core\App\Log;

/**
 * Protobuf type <code>bluehead.v2ray.core.app.log.LogType</code>
 */
class LogType
{
    /**
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Generated from protobuf enum <code>Console = 1;</code>
     */
    const Console = 1;
    /**
     * Generated from protobuf enum <code>File = 2;</code>
     */
    const File = 2;
    /**
     * Generated from protobuf enum <code>Event = 3;</code>
     */
    const Event = 3;
}

