<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tcp/config.proto

namespace GPBMetadata\V2ray\Transport\Internet\Tcp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\V2ray\Common\Serial\TypedMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87020a237472616e73706f72742f696e7465726e65742f7463702f636f" .
            "6e6669672e70726f746f122a626c7565686561642e76327261792e636f72" .
            "652e7472616e73706f72742e696e7465726e65742e74637022580a06436f" .
            "6e66696712480a0f6865616465725f73657474696e677318022001280b32" .
            "2f2e626c7565686561642e76327261792e636f72652e636f6d6d6f6e2e73" .
            "657269616c2e54797065644d6573736167654a040801100242520a25636f" .
            "6d2e76327261792e636f72652e7472616e73706f72742e696e7465726e65" .
            "742e74637050015a03746370aa022156325261792e436f72652e5472616e" .
            "73706f72742e496e7465726e65742e546370620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

