<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/config.proto

namespace Bluehead\V2ray\GPBMetadata\App\Log;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Bluehead\V2ray\GPBMetadata\Common\Log\Log::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4030a146170702f6c6f672f636f6e6669672e70726f746f121b626c75" .
            "65686561642e76327261792e636f72652e6170702e6c6f6722f9010a0643" .
            "6f6e666967123c0a0e6572726f725f6c6f675f7479706518012001280e32" .
            "242e626c7565686561642e76327261792e636f72652e6170702e6c6f672e" .
            "4c6f675479706512410a0f6572726f725f6c6f675f6c6576656c18022001" .
            "280e32282e626c7565686561642e76327261792e636f72652e636f6d6d6f" .
            "6e2e6c6f672e536576657269747912160a0e6572726f725f6c6f675f7061" .
            "7468180320012809123d0a0f6163636573735f6c6f675f74797065180420" .
            "01280e32242e626c7565686561642e76327261792e636f72652e6170702e" .
            "6c6f672e4c6f675479706512170a0f6163636573735f6c6f675f70617468" .
            "1805200128092a350a074c6f675479706512080a044e6f6e651000120b0a" .
            "07436f6e736f6c65100112080a0446696c65100212090a054576656e7410" .
            "0342340a16636f6d2e76327261792e636f72652e6170702e6c6f6750015a" .
            "036c6f67aa021256325261792e436f72652e4170702e4c6f67620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

