<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/outbound/config.proto

namespace Bluehead\V2ray\Core\Proxy\Vmess\Outbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.vmess.outbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.ServerEndpoint Receiver = 1;</code>
     */
    private $Receiver;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bluehead\V2ray\Core\Common\Protocol\ServerEndpoint[]|\Google\Protobuf\Internal\RepeatedField $Receiver
     * }
     */
    public function __construct($data = NULL) {
        \Bluehead\V2ray\GPBMetadata\Proxy\Vmess\Outbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.ServerEndpoint Receiver = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReceiver()
    {
        return $this->Receiver;
    }

    /**
     * Generated from protobuf field <code>repeated .bluehead.v2ray.core.common.protocol.ServerEndpoint Receiver = 1;</code>
     * @param \Bluehead\V2ray\Core\Common\Protocol\ServerEndpoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReceiver($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bluehead\V2ray\Core\Common\Protocol\ServerEndpoint::class);
        $this->Receiver = $arr;

        return $this;
    }

}

