<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/http/config.proto

namespace Bluehead\V2ray\Core\Proxy\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Config for HTTP proxy server.
 *
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.http.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 timeout = 1 [deprecated = true];</code>
     */
    private $timeout = 0;
    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     */
    private $accounts;
    /**
     * Generated from protobuf field <code>bool allow_transparent = 3;</code>
     */
    private $allow_transparent = false;
    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     */
    private $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $timeout
     *     @type array|\Google\Protobuf\Internal\MapField $accounts
     *     @type bool $allow_transparent
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Proxy\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 1 [deprecated = true];</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 1 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->accounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_transparent = 3;</code>
     * @return bool
     */
    public function getAllowTransparent()
    {
        return $this->allow_transparent;
    }

    /**
     * Generated from protobuf field <code>bool allow_transparent = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowTransparent($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_transparent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

