<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/log/command/config.proto

namespace Bluehead\V2ray\GPBMetadata\App\Log\Command;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed020a1c6170702f6c6f672f636f6d6d616e642f636f6e6669672e7072" .
            "6f746f1223626c7565686561642e76327261792e636f72652e6170702e6c" .
            "6f672e636f6d6d616e6422080a06436f6e66696722160a14526573746172" .
            "744c6f676765725265717565737422170a15526573746172744c6f676765" .
            "72526573706f6e7365329a010a0d4c6f6767657253657276696365128801" .
            "0a0d526573746172744c6f6767657212392e626c7565686561642e763272" .
            "61792e636f72652e6170702e6c6f672e636f6d6d616e642e526573746172" .
            "744c6f67676572526571756573741a3a2e626c7565686561642e76327261" .
            "792e636f72652e6170702e6c6f672e636f6d6d616e642e52657374617274" .
            "4c6f67676572526573706f6e7365220042480a1e636f6d2e76327261792e" .
            "636f72652e6170702e6c6f672e636f6d6d616e6450015a07636f6d6d616e" .
            "64aa021a56325261792e436f72652e4170702e4c6f672e436f6d6d616e64" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

