<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/log/log.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Log;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a14636f6d6d6f6e2f6c6f672f6c6f672e70726f746f121e626c75" .
            "65686561642e76327261792e636f72652e636f6d6d6f6e2e6c6f672a440a" .
            "085365766572697479120b0a07556e6b6e6f776e100012090a054572726f" .
            "721001120b0a075761726e696e67100212080a04496e666f100312090a05" .
            "44656275671004423a0a19636f6d2e76327261792e636f72652e636f6d6d" .
            "6f6e2e6c6f6750015a036c6f67aa021556325261792e436f72652e436f6d" .
            "6d6f6e2e4c6f67620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

