<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Bluehead\V2ray\Core\App\Router\Config;

/**
 * Protobuf type <code>bluehead.v2ray.core.app.router.Config.DomainStrategy</code>
 */
class DomainStrategy
{
    /**
     * Use domain as is.
     *
     * Generated from protobuf enum <code>AsIs = 0;</code>
     */
    const AsIs = 0;
    /**
     * Always resolve IP for domains.
     *
     * Generated from protobuf enum <code>UseIp = 1;</code>
     */
    const UseIp = 1;
    /**
     * Resolve to IP if the domain doesn't match any rules.
     *
     * Generated from protobuf enum <code>IpIfNonMatch = 2;</code>
     */
    const IpIfNonMatch = 2;
    /**
     * Resolve to IP if any rule requires IP matching.
     *
     * Generated from protobuf enum <code>IpOnDemand = 3;</code>
     */
    const IpOnDemand = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DomainStrategy::class, \Bluehead\V2ray\Core\App\Router\Config_DomainStrategy::class);

