<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/inbound/config.proto

namespace GPBMetadata\V2ray\Proxy\Vmess\Inbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\V2ray\Common\Protocol\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7030a2070726f78792f766d6573732f696e626f756e642f636f6e6669" .
            "672e70726f746f1227626c7565686561642e76327261792e636f72652e70" .
            "726f78792e766d6573732e696e626f756e64221a0a0c4465746f7572436f" .
            "6e666967120a0a02746f18012001280922300a0d44656661756c74436f6e" .
            "66696712100a08616c7465725f696418012001280d120d0a056c6576656c" .
            "18022001280d22f1010a06436f6e66696712370a04757365721801200328" .
            "0b32292e626c7565686561642e76327261792e636f72652e636f6d6d6f6e" .
            "2e70726f746f636f6c2e5573657212470a0764656661756c741802200128" .
            "0b32362e626c7565686561642e76327261792e636f72652e70726f78792e" .
            "766d6573732e696e626f756e642e44656661756c74436f6e66696712450a" .
            "066465746f757218032001280b32352e626c7565686561642e7632726179" .
            "2e636f72652e70726f78792e766d6573732e696e626f756e642e4465746f" .
            "7572436f6e666967121e0a167365637572655f656e6372797074696f6e5f" .
            "6f6e6c7918042001280842500a22636f6d2e76327261792e636f72652e70" .
            "726f78792e766d6573732e696e626f756e6450015a07696e626f756e64aa" .
            "021e56325261792e436f72652e50726f78792e566d6573732e496e626f75" .
            "6e64620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

