<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/websocket/config.proto

namespace GPBMetadata\V2ray\Transport\Internet\Websocket;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9020a297472616e73706f72742f696e7465726e65742f776562736f63" .
            "6b65742f636f6e6669672e70726f746f1230626c7565686561642e763272" .
            "61792e636f72652e7472616e73706f72742e696e7465726e65742e776562" .
            "736f636b657422240a06486561646572120b0a036b657918012001280912" .
            "0d0a0576616c756518022001280922660a06436f6e666967120c0a047061" .
            "746818022001280912480a0668656164657218032003280b32382e626c75" .
            "65686561642e76327261792e636f72652e7472616e73706f72742e696e74" .
            "65726e65742e776562736f636b65742e4865616465724a04080110024264" .
            "0a2b636f6d2e76327261792e636f72652e7472616e73706f72742e696e74" .
            "65726e65742e776562736f636b657450015a09776562736f636b6574aa02" .
            "2756325261792e436f72652e5472616e73706f72742e496e7465726e6574" .
            "2e576562736f636b6574620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

