<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/destination.proto

namespace GPBMetadata\V2ray\Common\Net;

class Destination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\V2ray\Common\Net\Network::initOnce();
        \GPBMetadata\V2ray\Common\Net\Address::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae020a1c636f6d6d6f6e2f6e65742f64657374696e6174696f6e2e7072" .
            "6f746f121e626c7565686561642e76327261792e636f72652e636f6d6d6f" .
            "6e2e6e65741a18636f6d6d6f6e2f6e65742f616464726573732e70726f74" .
            "6f228f010a08456e64706f696e7412380a076e6574776f726b1801200128" .
            "0e32272e626c7565686561642e76327261792e636f72652e636f6d6d6f6e" .
            "2e6e65742e4e6574776f726b123b0a076164647265737318022001280b32" .
            "2a2e626c7565686561642e76327261792e636f72652e636f6d6d6f6e2e6e" .
            "65742e49504f72446f6d61696e120c0a04706f727418032001280d423a0a" .
            "19636f6d2e76327261792e636f72652e636f6d6d6f6e2e6e657450015a03" .
            "6e6574aa021556325261792e436f72652e436f6d6d6f6e2e4e6574620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

