<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/network.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Net;

class Network
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81020a18636f6d6d6f6e2f6e65742f6e6574776f726b2e70726f746f12" .
            "1e626c7565686561642e76327261792e636f72652e636f6d6d6f6e2e6e65" .
            "7422470a0b4e6574776f726b4c69737412380a076e6574776f726b180120" .
            "03280e32272e626c7565686561642e76327261792e636f72652e636f6d6d" .
            "6f6e2e6e65742e4e6574776f726b2a380a074e6574776f726b120b0a0755" .
            "6e6b6e6f776e1000120e0a0652617754435010011a02080112070a035443" .
            "50100212070a035544501003423a0a19636f6d2e76327261792e636f7265" .
            "2e636f6d6d6f6e2e6e657450015a036e6574aa021556325261792e436f72" .
            "652e436f6d6d6f6e2e4e6574620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

