<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/port.proto

namespace Bluehead\V2ray\GPBMetadata\Common\Net;

class Port
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a15636f6d6d6f6e2f6e65742f706f72742e70726f746f121e626c" .
            "7565686561642e76327261792e636f72652e636f6d6d6f6e2e6e65742225" .
            "0a09506f727452616e6765120c0a0446726f6d18012001280d120a0a0254" .
            "6f18022001280d423a0a19636f6d2e76327261792e636f72652e636f6d6d" .
            "6f6e2e6e657450015a036e6574aa021556325261792e436f72652e436f6d" .
            "6d6f6e2e4e6574620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

