<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/socks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Socks;

/**
 * Protobuf type <code>bluehead.v2ray.core.proxy.socks.AuthType</code>
 */
class AuthType
{
    /**
     * Generated from protobuf enum <code>NO_AUTH = 0;</code>
     */
    const NO_AUTH = 0;
    /**
     * Generated from protobuf enum <code>PASSWORD = 1;</code>
     */
    const PASSWORD = 1;
}

