<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/socks/config.proto

namespace Bluehead\V2ray\Core\Proxy\Socks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluehead.v2ray.core.proxy.socks.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     */
    private $auth_type = 0;
    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     */
    private $accounts;
    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 3;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     */
    private $udp_enabled = false;
    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     */
    private $timeout = 0;
    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     */
    private $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $auth_type
     *     @type array|\Google\Protobuf\Internal\MapField $accounts
     *     @type \Bluehead\V2ray\Core\Common\Net\IPOrDomain $address
     *     @type bool $udp_enabled
     *     @type int $timeout
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2ray\Proxy\Socks\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     * @return int
     */
    public function getAuthType()
    {
        return $this->auth_type;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthType($var)
    {
        GPBUtil::checkEnum($var, \Bluehead\V2ray\Core\Proxy\Socks\AuthType::class);
        $this->auth_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->accounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @return \Bluehead\V2ray\Core\Common\Net\IPOrDomain
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.bluehead.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @param \Bluehead\V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Bluehead\V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @return bool
     */
    public function getUdpEnabled()
    {
        return $this->udp_enabled;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUdpEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->udp_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

